# Example configuration file for eks-auto-pod-id-assoc

clusters:
  - region: us-east-1
    annotation: eks.amazonaws.com/role-arn
    exclude_service_accounts:
      # exclude any service account from namespace kube-system
      - namespace: ^kube-system$

  # # use a specific role to access a specific cluster
  # - role_arn: arn:aws:iam::123456789012:role/AnotherRole
  #   region: us-east-1
  #   cluster_name: ^example-cluster-2$ # exact cluster name

  # # use default role and discover all clusters in the region
  # - region: sa-east-1
  #   cluster_name: ^my- # only clusters starting with "my-"

  # # use the cluster where we are running
  # - self: true
  #   cluster_name: my-cluster # with self use EXACT cluster name (NO REGEX)
