apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: eks-auto-pod-id-assoc
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: eks-auto-pod-id-assoc
subjects:
- kind: ServiceAccount
  name: eks-auto-pod-id-assoc
  namespace: default
