apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "eks-auto-pod-id-assoc.fullname" . }}
  labels:
    {{- include "eks-auto-pod-id-assoc.labels" . | nindent 4 }}
  {{- if or .Values.serviceAccountAnnotations }}
  annotations:
  {{- end }}
    {{- with .Values.serviceAccountAnnotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
